### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by camphousemarketing**
Hey Caleb! 

This pull request includes the elimination of the Puppy and Basic Packages, an update to the about section, and a couple of removals in the Add-Ons section. I only updated the index.html file so if other changes to the CSS need to be made let me know. I will send an email to you and Missie which summarizes these changes.

### CODE REVIEW

**Comment by likens** [comment]
On resolutions 1200px and larger, the removal of the Puppy and Basic packages causes a large gap that needs addressed in the HTML/CSS. I recommend splitting out the Add-ons and Al-a-carte into their own sections to compensate (add-ons might be quite sparse though). See issue below.

image

**Comment by likens** [comment]
Also, in backup/index.html, I try to keep the unminified index.html file as a backup. Please update that as well. Thanks!

**Comment by camphousemarketing** [comment]
I have updated the backup file as you requested. I went in to the styles.css file and noticed at 1200 px, that section had 4 columns defined. I changed that to two. As far as a-la-carte and add-ons are concerned, I wonder if we could just have it as a single section titled "Additional Services"? I can reach out and inquire. 

Let me know if you need me to make any additional changes!

**Comment by likens** [comment]
It's up to Missy and you for how this is laid out, I'm just here for the hosting/infra unless you move it somewhere else.

Your CSS change has caused a different style issue for 1200px and up:
image

This repo also utilizes Scss to compile the CSS. Those file(s) will need updated as well and are compiled to the make the end minified CSS result. Use [Prepros](https://prepros.io/) for a quick application that compile that.

**Comment by camphousemarketing** [comment]
Hey Caleb! Prepros was great. I've updated the CSS to have the extras span both columns. I've also updated the SCSS to reflect all changes made in the services section.

**Comment by likens** [comment]
Looking better... if I had one last recommendation comment it would be:

- On .service__list, drop the max-width to ~80-100 rem, right now its way too wide to look good
- Since you reduced the number of columns in .service__list for 1200px MQ to 2, might as well remove that since 600px MQ is already at 2

If we get that cleaned up, I think it's good to go for a merge.

**Comment by camphousemarketing** [comment]
Hey Caleb! Thanks for the suggestions. I've made those edits to both the CSS and SCSS main files.

**Comment by likens** [comment]
I was about to merge the PR and after checking one more time, I just noticed that the footer is really messed up. I think you might not have tags fully closed. I recommend taking the unminified backup, verifying it works, then once all is done, minify it for the actual one:

image

**Comment by camphousemarketing** [comment]
Hey Caleb! Thanks for pointing that out. I believe the issue is resolved. There was an unnecessary Media Break in the minified styles.css.

**Pull request merged**
